'use client'

import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'

import { Activity, ArrowRight, CreditCard, Headphones, Plus, Zap } from 'lucide-react'
import { sectionLabels } from '@/lib/demo-data'
import Table from '@/components/records-table'
import CreditsLedger from '@/components/credits-ledger'
import WorkspaceExtras from '@/components/workspace-extras'
import WorkspaceSearch from '@/components/workspace-search'

function Overview() { return <><div className="welcome"><div><p className="eyebrow">MONDAY, 24 MARCH 2025</p><h1>Good morning, Jane</h1><p className="welcome-sub">Here&apos;s what&apos;s happening with your marketing workspace.</p></div><Link className="primary" href="/tasks/new"><Plus size={18} /> Request a task</Link></div><div className="stats"><div className="stat card"><div className="stat-icon red"><CreditCard size={19} /></div><div><p>Active subscription</p><strong>Growth plan</strong><small>Renews 29 Mar 2025</small></div></div><div className="stat card"><div className="stat-icon orange"><Zap size={19} /></div><div><p>Credits remaining</p><strong>18.5 credits</strong><small>of 30 credits this month</small></div></div><div className="stat card"><div className="stat-icon blue"><Activity size={19} /></div><div><p>Tasks in progress</p><strong>4 tasks</strong><small>2 awaiting your review</small></div></div><div className="stat card"><div className="stat-icon purple"><Headphones size={19} /></div><div><p>Open tickets</p><strong>2 tickets</strong><small>Latest reply 2 hours ago</small></div></div></div><section className="panel card"><div className="panel-head"><div><h2>Recent tasks</h2><p>1 credit = 1 hour of completed work</p></div><Link className="text-button" href="/tasks">View all <ArrowRight size={16} /></Link></div><Table section="tasks" /></section></> }
function RefreshButton() { const router = useRouter(); return <button className="primary" onClick={() => router.refresh()}><Plus size={18} />Refresh</button> }
export default function Page() { const path = usePathname(); const section = path.slice(1); const isOverview = !section || section === 'overview'; return <>{isOverview ? <Overview /> : section === 'credits' ? <CreditsLedger /> : section === 'search' ? <WorkspaceSearch /> : ['help', 'support', 'settings'].includes(section) ? <WorkspaceExtras key={section} section={section} /> : <><div className="welcome"><div><p className="eyebrow">FIRST PERSON MARKETING</p><h1>{sectionLabels[section] ?? 'Workspace'}</h1><p className="welcome-sub">Manage your {sectionLabels[section]?.toLowerCase() ?? 'workspace records'}.</p></div>{section === 'tasks' ? <Link className="primary" href="/tasks/new"><Plus size={18} />Request a task</Link> : section === 'projects' ? <Link className="primary" href="/projects/new"><Plus size={18} />Add project</Link> : <RefreshButton />}</div><section className="panel card"><div className="panel-head"><div><h2>{sectionLabels[section] ?? 'Workspace records'}</h2><p>{section === 'credits' ? '1 credit equals 1 hour of completed work.' : 'Select a record to view its full details.'}</p></div></div><Table section={section} /></section></>}</> }
