'use client'

import Link from 'next/link'
import { useState } from 'react'
import { Activity, ArrowRight, Bell, CheckCircle2, ChevronRight, CircleHelp, CreditCard, FileText, Grid2X2, Headphones, House, Menu, Plus, Search, Settings, Ticket, WalletCards, X, Zap } from 'lucide-react'
import { records, sectionLabels } from '@/lib/demo-data'

const nav = [{ label: 'Overview', href: '/', icon: House }, { label: 'Subscriptions', href: '/subscriptions', icon: CreditCard }, { label: 'Tasks', href: '/tasks', icon: CheckCircle2 }, { label: 'Credits', href: '/credits', icon: Zap }, { label: 'Support tickets', href: '/tickets', icon: Ticket }, { label: 'Invoices', href: '/invoices', icon: FileText }]

function Brand() { return <div className="brand"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/IMG_1712-DPupM5FLesuxf6YstfDbnd9g8opHU7.png" alt="First Person Marketing" /></div> }
function Sidebar({ open, close }: { open: boolean; close: () => void }) { return <><button className={`overlay ${open ? 'show' : ''}`} onClick={close} aria-label="Close navigation" /><aside className={`sidebar ${open ? 'open' : ''}`}><div className="side-head"><Brand /><button className="close" onClick={close} aria-label="Close navigation"><X size={20} /></button></div><nav><p className="nav-section">GENERAL</p>{nav.slice(0, 2).map(({ label, href, icon: Icon }) => <Link className="nav-link" href={href} key={label} onClick={close}><Icon size={18} /><span>{label}</span></Link>)}<p className="nav-section">WORK MANAGEMENT</p>{nav.slice(2, 5).map(({ label, href, icon: Icon }) => <Link className="nav-link" href={href} key={label} onClick={close}><Icon size={18} /><span>{label}</span></Link>)}<p className="nav-section">ACCOUNT</p><Link className="nav-link" href="/invoices" onClick={close}><FileText size={18} /><span>Invoices</span></Link></nav><div className="side-footer"><button className="nav-link"><CircleHelp size={18} /><span>Help center</span></button><button className="nav-link"><Settings size={18} /><span>Settings</span></button><div className="user"><span className="avatar">JD</span><div><strong>Jane Doe</strong><small>Admin</small></div></div></div></aside></> }
function Header({ onMenu }: { onMenu: () => void }) { return <header className="header"><button className="menu" onClick={onMenu} aria-label="Open navigation"><Menu size={21} /></button><div className="search"><Search size={17} /><span>Search tasks, invoices, tickets...</span></div><div className="header-right"><button className="icon-button"><Grid2X2 size={19} /></button><button className="icon-button notification"><Bell size={19} /><i /></button><span className="header-user">Jane Doe</span><span className="avatar small">JD</span></div></header> }
function Table({ section }: { section: string }) { const rows = records[section] ?? []; return <div className="table-wrap"><table><thead><tr><th>Details</th><th>Status</th><th>Value</th><th>Updated</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><Link className="task-name" href={`/${section}/${row.id}`}><span className="task-dot" /><span><strong>{row.title}</strong><small>{row.meta}</small></span></Link></td><td><span className={`status ${row.status.toLowerCase().replaceAll(' ', '-')}`}>{row.status}</span></td><td>{row.value}</td><td>{row.date}</td><td><Link href={`/${section}/${row.id}`} aria-label={`Open ${row.title}`}><ChevronRight size={16} /></Link></td></tr>)}</tbody></table></div> }
function Overview() { return <><div className="welcome"><div><p className="eyebrow">MONDAY, 24 MARCH 2025</p><h1>Good morning, Jane</h1><p className="welcome-sub">Here&apos;s what&apos;s happening with your marketing workspace.</p></div><Link className="primary" href="/tasks/new"><Plus size={18} /> Request a task</Link></div><div className="stats"><div className="stat card"><div className="stat-icon red"><CreditCard size={19} /></div><div><p>Active subscription</p><strong>Growth plan</strong><small>Renews 29 Mar 2025</small></div></div><div className="stat card"><div className="stat-icon orange"><Zap size={19} /></div><div><p>Credits remaining</p><strong>18.5 credits</strong><small>of 30 credits this month</small></div></div><div className="stat card"><div className="stat-icon blue"><Activity size={19} /></div><div><p>Tasks in progress</p><strong>4 tasks</strong><small>2 awaiting your review</small></div></div><div className="stat card"><div className="stat-icon purple"><Headphones size={19} /></div><div><p>Open tickets</p><strong>2 tickets</strong><small>Latest reply 2 hours ago</small></div></div></div><section className="panel card"><div className="panel-head"><div><h2>Recent tasks</h2><p>1 credit = 1 hour of completed work</p></div><Link className="text-button" href="/tasks">View all <ArrowRight size={16} /></Link></div><Table section="tasks" /></section></> }
export default function Page() { const [open, setOpen] = useState(false); const path = typeof window === 'undefined' ? '/' : window.location.pathname; const section = path.slice(1); const isOverview = !section || section === 'overview'; return <main className="app"><Sidebar open={open} close={() => setOpen(false)} /><div className="shell"><Header onMenu={() => setOpen(true)} /><div className="page">{isOverview ? <Overview /> : <><div className="welcome"><div><p className="eyebrow">FIRST PERSON MARKETING</p><h1>{sectionLabels[section] ?? 'Workspace'}</h1><p className="welcome-sub">Manage your {sectionLabels[section]?.toLowerCase() ?? 'workspace records'}.</p></div><Link className="primary" href={section === 'tasks' ? '/tasks/new' : `/${section}`}><Plus size={18} /> {section === 'tasks' ? 'Request a task' : 'Refresh'}</Link></div><section className="panel card"><div className="panel-head"><div><h2>{sectionLabels[section] ?? 'Workspace records'}</h2><p>{section === 'credits' ? '1 credit equals 1 hour of completed work.' : 'Select a record to view its full details.'}</p></div></div><Table section={section} /></section></>}</div></div></main> }
