'use client'

import Link from 'next/link'
import { useEffect, useState, type FormEvent } from 'react'
import { ArrowRight, CircleHelp, Ticket } from 'lucide-react'

const questions = [
  ['How do I request work?', 'Open Tasks and choose Request a task. Include the goal, audience, required deliverables, and any relevant deadlines in your brief.'],
  ['How are credits measured?', 'One credit represents one hour of completed work. The Credits page shows your remaining allowance and reset date.'],
  ['Where can I review task progress?', 'The Tasks page lists each request and its status. Select a task to open its details.'],
  ['Where can I find billing information?', 'Open Subscriptions for your plan and renewal information, or Invoices to review billing records.'],
]
const countries = ['Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda','Argentina','Armenia','Australia','Austria','Azerbaijan','Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium','Belize','Benin','Bhutan','Bolivia','Bosnia and Herzegovina','Botswana','Brazil','Brunei','Bulgaria','Burkina Faso','Burundi','Cabo Verde','Cambodia','Cameroon','Canada','Central African Republic','Chad','Chile','China','Colombia','Comoros','Congo','Costa Rica','Côte d’Ivoire','Croatia','Cuba','Cyprus','Czechia','Democratic Republic of the Congo','Denmark','Djibouti','Dominica','Dominican Republic','Ecuador','Egypt','El Salvador','Equatorial Guinea','Eritrea','Estonia','Eswatini','Ethiopia','Fiji','Finland','France','Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala','Guinea','Guinea-Bissau','Guyana','Haiti','Honduras','Hungary','Iceland','India','Indonesia','Iran','Iraq','Ireland','Israel','Italy','Jamaica','Japan','Jordan','Kazakhstan','Kenya','Kiribati','Kuwait','Kyrgyzstan','Laos','Latvia','Lebanon','Lesotho','Liberia','Libya','Liechtenstein','Lithuania','Luxembourg','Madagascar','Malawi','Malaysia','Maldives','Mali','Malta','Marshall Islands','Mauritania','Mauritius','Mexico','Micronesia','Moldova','Monaco','Mongolia','Montenegro','Morocco','Mozambique','Myanmar','Namibia','Nauru','Nepal','Netherlands','New Zealand','Nicaragua','Niger','Nigeria','North Korea','North Macedonia','Norway','Oman','Pakistan','Palau','Palestine','Panama','Papua New Guinea','Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Romania','Russia','Rwanda','Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Samoa','San Marino','São Tomé and Príncipe','Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone','Singapore','Slovakia','Slovenia','Solomon Islands','Somalia','South Africa','South Korea','South Sudan','Spain','Sri Lanka','Sudan','Suriname','Sweden','Switzerland','Syria','Tajikistan','Tanzania','Thailand','Timor-Leste','Togo','Tonga','Trinidad and Tobago','Tunisia','Türkiye','Turkmenistan','Tuvalu','Uganda','Ukraine','United Arab Emirates','United Kingdom','United States','Uruguay','Uzbekistan','Vanuatu','Vatican City','Venezuela','Vietnam','Yemen','Zambia','Zimbabwe']

function SettingsForm() {
  const [name, setName] = useState('Jane Doe')
  const [workspace, setWorkspace] = useState('First Person Marketing')
  const [email, setEmail] = useState('jane@example.com')
  const [phone, setPhone] = useState('')
  const [businessName, setBusinessName] = useState('')
  const [website, setWebsite] = useState('')
  const [tab, setTab] = useState<'personal' | 'business' | 'agreement' | 'guarantee'>('personal')
  const [claimStatus, setClaimStatus] = useState('Not submitted')
  const [message, setMessage] = useState('')
  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem('fpm-workspace-settings') ?? 'null')
      if (typeof saved?.name === 'string') setName(saved.name)
      if (typeof saved?.workspace === 'string') setWorkspace(saved.workspace)
      if (typeof saved?.email === 'string') setEmail(saved.email)
      if (typeof saved?.phone === 'string') setPhone(saved.phone)
      if (typeof saved?.businessName === 'string') setBusinessName(saved.businessName)
      if (typeof saved?.website === 'string') setWebsite(saved.website)
      if (localStorage.getItem('fpm-money-back-claim') === 'under-review') setClaimStatus('Under review')
    } catch { setMessage('Saved preferences could not be loaded.') }
  }, [])
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { localStorage.setItem('fpm-workspace-settings', JSON.stringify({ name, workspace, email, phone, businessName, website })); setMessage('Settings saved in this browser.') } catch { setMessage('Unable to save preferences. Check your browser storage settings.') } }
  return <section className="card workspace-content settings-content"><div className="settings-tabs" role="tablist">{[['personal', 'Personal information'], ['business', 'Business information'], ['agreement', 'Agreement'], ['guarantee', '90 Day Money Back']].map(([id, label]) => <button key={id} role="tab" type="button" aria-selected={tab === id} className={tab === id ? 'selected' : ''} onClick={() => setTab(id as typeof tab)}>{label}</button>)}</div>
    {tab === 'personal' && <form className="request-form" onSubmit={save}><div><h2>Personal information</h2><p className="welcome-sub">The primary contact used for task updates, billing notices, and support requests.</p></div><div className="table-wrap"><table className="data-table settings-summary-table"><thead><tr><th>Client ID</th><th>Account status</th><th>Member since</th></tr></thead><tbody><tr><td className="record-reference">CLT-82374101</td><td>Active</td><td>01 Mar 2025</td></tr></tbody></table></div><div className="settings-readonly"><h3>Account identity</h3><label>Account email<input type="email" value={email} readOnly aria-readonly="true" /></label><label>Client role<input value="Account owner" readOnly aria-readonly="true" /></label><p>These fields are managed by your account team. Contact support if they need to be changed.</p></div><div className="settings-editable"><h3>Contact preferences</h3><label>Full name<input required value={name} onChange={event => { setName(event.target.value); setMessage('') }} /></label><label>Phone number<input inputMode="tel" value={phone} onChange={event => { setPhone(event.target.value); setMessage('') }} /></label><label>Job title<input placeholder="e.g. Marketing Director" /></label><label>Preferred contact method<select defaultValue="Email"><option>Email</option><option>Phone</option></select></label></div><div><button className="primary" type="submit">Save contact preferences</button></div><p role="status">{message}</p></form>}
    {tab === 'business' && <form className="request-form" onSubmit={save}><div><h2>Business information</h2><p className="welcome-sub">Business details are used for account records, invoices, and service communications.</p></div><label>Legal business name<input required value={businessName} onChange={event => { setBusinessName(event.target.value); setMessage('') }} /></label><label>Workspace name<input required value={workspace} onChange={event => { setWorkspace(event.target.value); setMessage('') }} /></label><label>Website<input type="url" placeholder="https://example.com" value={website} onChange={event => { setWebsite(event.target.value); setMessage('') }} /></label><label>Billing email<input type="email" value={email} readOnly aria-readonly="true" /></label><div className="address-fields"><label>Address line 1<input required placeholder="Street address" /></label><label>Address line 2<input placeholder="Suite, unit, or floor" /></label><label>City<input required /></label><label>State / province<input /></label><label>Postal code<input required /></label><label>Country<select defaultValue=""><option value="" disabled>Select country</option>{countries.map(country => <option key={country}>{country}</option>)}</select></label></div><label>Tax or registration number<input placeholder="Optional" /></label><div><button className="primary" type="submit">Save business information</button></div><p role="status">{message}</p></form>}
    {tab === 'agreement' && <div className="settings-panel"><h2>Service agreement</h2><p className="ops-copy">Your binding service agreement governs scope of work, delivery approvals, payment terms, confidentiality, intellectual property, and account responsibilities.</p><dl className="ops-facts"><div><dt>Agreement status</dt><dd>Active</dd></div><div><dt>Agreement reference</dt><dd className="record-reference">AGR-82374101</dd></div><div><dt>Agreement version</dt><dd>v1.0</dd></div><div><dt>Effective date</dt><dd>01 Mar 2025</dd></div><div><dt>Client legal entity</dt><dd>First Person Marketing</dd></div><div><dt>Authorised signatory</dt><dd>Jane Doe · Account owner</dd></div><div><dt>Signed date</dt><dd>01 Mar 2025</dd></div><div><dt>Service term</dt><dd>Monthly recurring</dd></div><div><dt>Notice period</dt><dd>30 days</dd></div><div><dt>Governing law</dt><dd>England and Wales</dd></div><div><dt>Jurisdiction</dt><dd>Courts of England and Wales</dd></div></dl><button className="outline-button" type="button">Download agreement</button></div>}
    {tab === 'guarantee' && <div className="settings-panel"><div><h2>90 Day Money Back</h2><p className="ops-copy">A claim may be submitted after the 90-day service period where invoices were paid on time, no payment failed, and no conversions were recorded.</p></div><div className="table-wrap"><table className="data-table guarantee-table"><thead><tr><th>Service</th><th>Service period</th><th>Guarantee status</th><th>Eligibility date</th></tr></thead><tbody><tr><td>Growth monthly service</td><td>01 Mar–29 May 2025</td><td><span className="status in-progress">Pending service period</span></td><td>30 May 2025</td></tr></tbody></table></div><dl className="ops-facts"><div><dt>Invoice requirement</dt><dd>All invoices paid on time</dd></div><div><dt>Payment requirement</dt><dd>No failed payments</dd></div><div><dt>Performance requirement</dt><dd>No conversions recorded</dd></div><div><dt>Claim status</dt><dd>{claimStatus}</dd></div></dl><Link className="primary" href="/settings/money-back/claim">{claimStatus === 'Under review' ? 'View claim status' : 'Check eligibility and submit claim'}</Link></div>}
  </section>
}

export default function WorkspaceExtras({ section }: { section: string }) {
  const title = section === 'help' ? 'Help center' : section === 'support' ? 'Support' : 'Settings'
  return <>
    <div className="welcome"><div><p className="eyebrow">FIRST PERSON MARKETING</p><h1>{title}</h1><p className="welcome-sub">{section === 'settings' ? 'Manage your workspace preferences.' : 'Find answers and keep your work moving.'}</p></div></div>
    {section === 'settings' ? <SettingsForm /> : <>
      <div className="support-options">
        <Link className="card support-option" href="/tickets"><Ticket size={22} /><h2>Support tickets</h2><p>Review your open conversations and ticket details.</p><span>View tickets <ArrowRight size={16} /></span></Link>
        <Link className="card support-option" href={section === 'help' ? '/tasks/new' : '/help'}><CircleHelp size={22} /><h2>{section === 'help' ? 'Request a task' : 'Help center'}</h2><p>{section === 'help' ? 'Prepare a brief for your next marketing task.' : 'Learn about tasks, credits, subscriptions, and billing.'}</p><span>{section === 'help' ? 'Create a brief' : 'Browse answers'} <ArrowRight size={16} /></span></Link>
      </div>
      <section className="card workspace-content"><h2>Frequently asked questions</h2><div className="help-questions">{questions.map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section>
    </>}
  </>
}
